# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 607d37c4f40615182485759260df613eefb4fa6701ac5a6519b12c9028afe6a5a040e736f3fdbd40ee77038ac65cb4b5875194a67c6e1c512e2527186788c2f9

test:
  secret_key_base: b1a249201bec937718b62c4a56151c6ab1d2c692f2b9c9acd794754aa41e0d0bf5ea0318885d18714dc40f1b61ba283e028c405706cffdd740da66b4d0f88081

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
